### ISSUE TITLE
update calculation of D for ESS plot

### ISSUE THREAD

**Issue by roblanf** [danlwarren/RWTY#119]
Sometimes there's no pattern and we fit an exponential distribution to pure noise, which can give use ~random ESS values.

To fix this, we should add a model comparison where we use AIC to compare:

1. A model with a y intercept and slope of 0
2. The exponential model

If model 2 is the best model, we proceed as usual.
If model 1 is the best model, we just return the smallest sampling interval as the value of D, and proceed accordingly.

**Comment by danlwarren** [comment]
I think this may require some modifications to the sampling intervals, because it seems like for the longest intervals we're getting a lot more spread than you have for the shorter ones.  I think this is artifactual, just due to smaller sample size for those longer intervals.  We should do some exploratory stuff with the salamander data set and see what the minimum sample size is to get good behaviour.

**Comment by danlwarren** [comment]
I'm wondering if it might be possible to coerce our data into a spatial object and use the fit.variogram functions in the gstat package.

**Comment by danlwarren** [comment]
Okay after dorking around with about a dozen different ways of doing this, it seems like the best answer that doesn't require a massive wodge of new imports is to just set the maximum sampling interval such that we get at least 100 tree distances per interval.  That seems to avoid the "variance trumpet", where longer intervals had noticeably higher variances.  Rob suggested that we might try subsampling so that each window had the same number of distances, but at present I'm not sure that's necessary; the new way seems to work fine on the test data.  We can revisit this if more pathological examples show up.
