### ISSUE TITLE
Include a second dataset, that is well behaved

### ISSUE THREAD

**Issue by roblanf** [danlwarren/RWTY#26]
The fungus dataset is horrible. And partly because of that is a bad example for some functions (e.g. calculating ESS, treespace).

It would be nice to have a second dataset that did converge, and that mixes well. Then our examples could compare and contrast the two datasets and serve as their own tutorial for each function.

I have some datasets I can contribute.

**Comment by danlwarren** [comment]
Done.  I've added two chains each from three loci from this study:

http://datadryad.org/resource/doi:10.5061/dryad.2gq14/1

It's a very interesting data set because each of the loci is well behaved on its own, but they're still a significant amount of disagreement between loci.  That seems like it's a big point of the original paper, so we're not showing anything new here, but IMO it makes it more interesting to play with and demonstrates the value of some of our methods even for people who have no problems with single-locus divergences.

**Comment by roblanf** [comment]
Hey @danlwarren, are there more chains than 2 in the original dataset? If so, do we have space to include a few more chains (even if it's only from one of the genes)? 

I ask only because demoing treespace plots is kinda cool with 4 panels. Not important. But kinda neat.

**Comment by danlwarren** [comment]
Not sure exactly what you mean.  The demo data has six chains, two each from three loci.  Do you mean include four chains for each of the three loci?  We can do that.  I might split the separate loci out into three separate objects, though, since most of the plots look like ass if you try to plot more than six or eight chains at once.

**Comment by roblanf** [comment]
OK no worries. Out of interest - which plots look bad with e.g. 8 chains? We can probably fix that...
