### ISSUE TITLE
Treespace function metrics

### ISSUE THREAD

**Issue by boopsboops** [danlwarren/RWTY#48]
In the 'treespace' function, the only available metric appears to be the RF symmetric distance (topology only), but sometimes if topologies are similar you might want to compare the variation in branch length estimation between runs. Therefore I hacked the 'branch score distance' metric to work, but this required phylip and the Rphylip package (so not ideal for rwty). And also, it's not appropriate to compare branch score distances between markers. 

So, I wonder if it was easy to add support for the 'K tree score' (Soria-Carrasco et al., 2007), or the new rooted metric by Kendall & Colijn (2015)?

Thanks!

P.S. great job on this package. I really like it!

**Comment by roblanf** [comment]
Sorry for the slow reply. 

In principle, one could create treespace plots with any metric. There are a couple of issues that I can see.

First, for your specific case of wanting to compare branch lengths, why not just compare plots of the tree length? This is already implemented in rwty. 

Second, if you really want to compare branch lengths in more detail than overall tree length, then the biggest issue to to compare like with like, e.g. by comparing the branch length for a particular split over the course of the MCMC. In principle we have all the machinery in rwty to do this, but it seems like it might not be that useful.

Third, metrics other than RF tend to be much more computationally expensive to calculate. In principle I'd  prefer (for just topology) to use something like an SPR distance or path distance over the RF distance. But I don't because they take a long time to calculate, and treespace plots scale as O(N-squared) with the number of trees. 

Finally, I actually think treespace plots that include branch lengths in the distance metric would be tricky to interpret. Often, a worse topology will also have longer branches, because it will take more changes to explain an incorrect tree. 

I guess I remain to be convinced that treespace plots that incorporate branch lengths are actually useful for anything. As far as I can tell, their utility is that they give a rough (sometimes very rough, since we reduce such a high dimensional graph to 2D) visual representation of what went on in the MCMC. They can sometimes help to diagnose issues. For example, if your two chains don't overlap much in treespace, there's probably something wrong with your MCMC. What I still don't know is what additional issues a metric like the K tree score would let users diagnose. Can you offer any clues here?

Unless there's a really strong case for a new metric (especially if that metric is expensive to calculate), I don't think there's much chance of us implementing anything. That said, if you want to to implement an option and submit a pull request, you're very welcome!

Either way, I'll leave this issue open, since it's certainly an interesting discussion.

**Comment by boopsboops** [comment]
Thanks Rob, you are absolutely right. Having thought about it, it doesn't make a great deal of sense to incorporate branch lengths into the treespace plots.

I am interested in comparing the variance in branch lengths among different markers, so it's more for data visualisation than MCMC diagnostics. Perhaps a better way to do that in a more comparable way is just to apply a relaxed clock and compare the HPDs of the dated node ages.
