### ISSUE TITLE
Issues loading in BEAST log.

### ISSUE THREAD

**Issue by wrightaprilm** [danlwarren/RWTY#62]
Hi all-

I had some issues with my headers not showing up when I read in BEAST logs. The issue isn't too hard to solve (load in log as table, save to $mytrees$myrun$ptable), but I thought it might be something you'd like to look at. My files are huge, and can be found here:

https://gitlab.com/trayc7/schiro-ind-study/commit/28c5f9e0ed692f67763290cc4968c3862bc8f184

nosa <- load.multi(".", ext.tree="trees", ext.p="log")

causes the header not to be read in.

**Comment by roblanf** [comment]
I still have this issue. I can't load BEAST logs. 

@danlwarren, can you take a look at this. It would be good to fix it before the ppr goes out for review, so that if someone tries to load BEAST files they work seamlessly. 

FWIW, I think we should aim at a minimum to have load.multi() work automatically with MrBayes and BEAST output.

To do that, we just need to look for '.trees' files for BEAST. If we find them, they should be associated with '.log' files. I can send you e.g. output from BEAST if you like.
